### PR TITLE
Update Renode patch for macOS

### PR DESCRIPTION
**Pull request by PiotrZierhoffer**

### CODE REVIEW

**Comment by mithro** [comment]
@PiotrZierhoffer LGTM - Merge if travis likes it!

**Comment by mithro** [comment]
You should log a bug on renode to upgrade to Python3 for the scripts too :-)

**Comment by PiotrZierhoffer** [comment]
@mithro  we are actively working on this, should be upstream very soon.

**Comment by PiotrZierhoffer** [comment]
Travis likes. Merged.

**Pull request merged**
